//
// Created by Busiu on 24.07.2018.
//

#ifndef SDLTEST_ENUMS_H
#define SDLTEST_ENUMS_H

enum KeyPressSurfaces{
    KEY_PRESS_SURFACE_DEFAULT = 0x0000,
    KEY_PRESS_SURFACE_UP,
    KEY_PRESS_SURFACE_DOWN,
    KEY_PRESS_SURFACE_LEFT,
    KEY_PRESS_SURFACE_RIGHT,
    KEY_PRESS_SURFACE_TOTAL,
};

#endif //SDLTEST_ENUMS_H
